[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[[bin]]
bench = false
name = "builder"

[build-dependencies]
types = { path = "../types" }
struct_inspect = { path = "../struct_inspect" }
