hard_tabs = true
tab_spaces = 2
newline_style = "Unix"
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
reorder_impl_items = true
use_field_init_shorthand = true
where_single_line = true
force_multiline_blocks = true
wrap_comments = true
