[package]
name = "struct_inspect_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features=["extra-traits"] }
quote = "1.0"
regex = "1"
