[package]
name = "layout_inspect_derive"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"
